export const ESSAY_META = {
  title: 'Turkana Boy: The First Modern Body',
  subtitle: '108 bones, one damaged jaw, and the child who made distance human',
  category: 'Science',
  subcategory: 'Paleoanthropology',
  readTime: '32 min',
  sourceCount: 16,
  sourceTier: 'Tier-1/2',
  sectionCount: 10,
  visualizationCount: 7,
  designSystem: 'Subject-derived',
  published: 'March 2026',
  model: 'gpt-5.4',
  spec: 'turkana-boy',
  variant: 'gpt-5-4',
  canonicalHref: '/essays/science/turkana-boy',
  template: 'Visual Essay',
  authorship: {
    mode: 'ai-directed' as const,
    director: { name: 'Zev Uhuru' },
    model: 'gpt-5.4',
    aiContributions: ['research', 'code', 'visualization'],
  },
  backLink: '/essays',
  backLabel: 'Essays',
  clusterParent: {
    slug: 'seven-million-years',
    title: 'Seven Million Years',
    route: '/essays/science/seven-million-years',
  },
  palette: [
    { name: 'Strata Dark', color: '#111317' },
    { name: 'Bone Ivory', color: '#E5D8C3' },
    { name: 'Sediment Sand', color: '#B9A387' },
    { name: 'Turkana Water', color: '#5E8D97' },
    { name: 'Heat Ochre', color: '#C97A3D' },
    { name: 'Charcoal Line', color: '#2A2F35' },
    { name: 'Dust Light', color: '#F4EBDD' },
    { name: 'Warning Rust', color: '#A95A3A' },
  ],
  visualizations: [
    { name: 'Skeletal Completeness Reveal', type: 'Interactive SVG' },
    { name: 'Age Discrepancy Comparison', type: 'D3 + SVG' },
    { name: 'Growth Projection Chart', type: 'Recharts Area Chart' },
    { name: 'Body Proportion Comparison', type: 'Recharts Bar Chart' },
    { name: 'Brain Volume Context', type: 'Recharts Bar Chart' },
    { name: 'Voice Debate Explainer', type: 'Annotated SVG' },
    { name: 'Migration Route Map', type: 'D3-Geo SVG' },
  ],
  keySources: [
    'Brown et al. 1985, Nature -- first report of KNM-WT 15000',
    'Walker and Leakey 1993 -- Nariokotome skeleton monograph',
    'Smith 2004 -- dental versus skeletal age',
    'Ruff and Walker 1993 -- body size and shape',
    'Wheeler 1993 -- thermoregulation and open-country body form',
    'Meyer and Haeusler 2015 -- caution on thoracic canal claims',
  ],
};
