export const IMAGES = {
  toumai: "https://images.esy.com/essays/seven-million-years/sahelanthropus-tchadensis-tm-266-01-060-1.e483c464d7.webp",
  ardi: "https://images.esy.com/essays/seven-million-years/ardipithecus-ramidus.92d6405a67.webp",
  lucy: "https://images.esy.com/essays/seven-million-years/lucy-blackbg.b7ae2af7ed.webp",
  laetoli: "https://images.esy.com/essays/seven-million-years/laetoli-footprints-replica.84894161b9.webp",
  paranthropusBoisei: "https://images.esy.com/essays/seven-million-years/paranthropus-boisei-skull.de00637e03.webp",
  olduvaiGorge: "https://images.esy.com/essays/seven-million-years/olduvai-gorge-or-oldupai-gorge.1974e1a31c.webp",
  turkanaboy: "https://images.esy.com/essays/seven-million-years/turkana-boy.9e197dcf2b.webp",
  handAxe: "https://images.esy.com/essays/seven-million-years/biface-de-st-acheul-mhnt.355866f02a.webp",
  homoNaledi: "https://images.esy.com/essays/seven-million-years/homo-naledi-skeletal-specimens.1151e1c05c.webp",
  neanderthal: "https://images.esy.com/essays/seven-million-years/homo-sapiens-neanderthalensis.19f3c601a5.webp",
  homoFloresiensis: "https://images.esy.com/essays/seven-million-years/homo-floresiensis.d762a7a22c.webp",
  lionMan: "https://images.esy.com/essays/seven-million-years/lion-man-photo.8297fd46fc.webp",
  dmanisiSkull: "https://images.esy.com/essays/seven-million-years/dmanisi-skull-1-8-mya-front.b0c91e0831.webp",
  levalloisFlake: "https://images.esy.com/essays/seven-million-years/levallois-flake-from-nesher-ramla.2d5be68d5f.webp",
  jebelIrhoud: "https://images.esy.com/essays/seven-million-years/homo-sapiens-from-jebel-irhoud.343246e8dd.webp",
  homoNalediDH1: "https://images.esy.com/essays/seven-million-years/homo-naledi-holotype-specimen-dh1.039951b9be.webp",
  greatRiftValley: "https://images.esy.com/essays/seven-million-years/great-rift-valley.d146141658.webp",
} as const;

export const IMAGE_CREDITS = [
  { subject: "Sahelanthropus tchadensis cranium", attribution: "Didier Descouens, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Sahelanthropus_tchadensis_-_TM_266-01-060-1.jpg" },
  { subject: "Ardipithecus ramidus skeleton cast", attribution: "Tiia Monto, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Ardipithecus_ramidus.jpg" },
  { subject: "Lucy skeleton (AL 288-1)", attribution: "120, CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:Lucy_blackbg.jpg" },
  { subject: "Laetoli footprints replica", attribution: "Tim Evanson, CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:Laetoli_footprints_replica.jpg" },
  { subject: "Paranthropus boisei skull", attribution: "Durova, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Paranthropus_boisei_skull.jpg" },
  { subject: "Olduvai Gorge panorama", attribution: "Noel Feans, CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Olduvai_Gorge_or_Oldupai_Gorge.jpg" },
  { subject: "Turkana Boy skeleton", attribution: "Bone Clones, CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:Turkana_Boy.jpg" },
  { subject: "Acheulean hand axe", attribution: "Didier Descouens, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Biface_de_St_Acheul_MHNT.jpg" },
  { subject: "Homo naledi skeletal specimens", attribution: "Lee Roger Berger et al., CC BY 4.0", url: "https://commons.wikimedia.org/wiki/File:Homo_naledi_skeletal_specimens.jpg" },
  { subject: "Neanderthal cranium", attribution: "Luna04, CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:Homo_sapiens_neanderthalensis.jpg" },
  { subject: "Homo floresiensis skull", attribution: "Ryan Somma, CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:Homo_floresiensis.jpg" },
  { subject: "Lion Man of Hohlenstein-Stadel", attribution: "Dagmar Hollmann, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Lion_man_photo.jpg" },
  { subject: "Dmanisi skull (1.8 MYA)", attribution: "Gerbil, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Dmanisi_skull_1.8_MYA_front.jpg" },
  { subject: "Levallois flake from Nesher Ramla", attribution: "Tal Rogovski, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Levallois_flake_from_Nesher_Ramla.jpg" },
  { subject: "Homo sapiens from Jebel Irhoud", attribution: "NHM London, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Homo_sapiens_from_Jebel_Irhoud.jpg" },
  { subject: "Homo naledi holotype cranium (DH1)", attribution: "Lee Roger Berger et al., CC BY 4.0", url: "https://commons.wikimedia.org/wiki/File:Homo_naledi_holotype_specimen_(DH1).jpg" },
  { subject: "Great Rift Valley aerial view", attribution: "Wikimedia Commons, CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Great_Rift_Valley.jpg" },
] as const;

export const SOURCES = [
  { id: "1", text: "Brunet, M., et al. (2002). A new hominid from the Upper Miocene of Chad, Central Africa. Nature, 418(6894), 145\u2013151." },
  { id: "2", text: "White, T.D., et al. (2009). Ardipithecus ramidus and the Paleobiology of Early Hominids. Science, 326(5949), 64\u201386." },
  { id: "3", text: "Johanson, D.C. & White, T.D. (1979). A systematic assessment of early African hominids. Science, 203(4378), 321\u2013330." },
  { id: "4", text: "Leakey, M.G., et al. (2001). New hominin genus from eastern Africa shows diverse middle Pliocene lineages. Nature, 410(6827), 433\u2013440." },
  { id: "5", text: "Berger, L.R., et al. (2015). Homo naledi, a new species of the genus Homo from the Dinaledi Chamber, South Africa. eLife, 4, e09560." },
  { id: "6", text: "Brown, P., et al. (2004). A new small-bodied hominin from the Late Pleistocene of Flores, Indonesia. Nature, 431(7012), 1055\u20131061." },
  { id: "7", text: "Hublin, J.-J., et al. (2017). New fossils from Jebel Irhoud, Morocco and the pan-African origin of Homo sapiens. Nature, 546(7657), 289\u2013292." },
  { id: "8", text: "Green, R.E., et al. (2010). A Draft Sequence of the Neandertal Genome. Science, 328(5979), 710\u2013722." },
  { id: "9", text: "Reich, D., et al. (2010). Genetic history of an archaic hominin group from Denisova Cave in Siberia. Nature, 468(7327), 1053\u20131060." },
  { id: "10", text: "Stringer, C. (2012). Lone Survivors: How We Came to Be the Only Humans on Earth. Times Books." },
  { id: "11", text: "Wood, B. & Richmond, B.G. (2000). Human evolution: taxonomy and paleobiology. Journal of Anatomy, 197(Pt 1), 19\u201360." },
  { id: "12", text: "Ant\u00f3n, S.C., Potts, R. & Aiello, L.C. (2014). Evolution of early Homo: An integrated biological perspective. Science, 345(6192), 1236828." },
  { id: "13", text: "Tattersall, I. (2012). Masters of the Planet: The Search for Our Human Origins. Palgrave Macmillan." },
  { id: "14", text: "Potts, R. (1998). Variability Selection in Hominid Evolution. Evolutionary Anthropology, 7(3), 81\u201396." },
  { id: "15", text: "Lordkipanidze, D., et al. (2013). A Complete Skull from Dmanisi, Georgia, and the Evolutionary Biology of Early Homo. Science, 342(6156), 326\u2013331." },
  { id: "16", text: "D\u00e9troit, F., et al. (2019). A new species of Homo from the Late Pleistocene of the Philippines. Nature, 568(7751), 181\u2013186." },
  { id: "17", text: "Ni, X., et al. (2021). Massive cranium from Harbin in northeastern China establishes a new Middle Pleistocene human lineage. The Innovation, 2(3), 100130." },
  { id: "18", text: "Harmand, S., et al. (2015). 3.3-million-year-old stone tools from Lomekwi 3, West Turkana, Kenya. Nature, 521(7552), 310\u2013315." },
  { id: "19", text: "Pr\u00fcfer, K., et al. (2014). The complete genome sequence of a Neanderthal from the Altai Mountains. Nature, 505(7481), 43\u201349." },
  { id: "20", text: "Rightmire, G.P. (2004). Brain size and encephalization in early to Mid-Pleistocene Homo. Am. J. Phys. Anthropol., 124(2), 109\u2013123." },
  { id: "21", text: "Mellars, P. (2006). Why did modern human populations disperse from Africa ca. 60,000 years ago? PNAS, 103(25), 9381\u20139386." },
  { id: "22", text: "Berger, L.R., et al. (2010). Australopithecus sediba: A New Species of Homo-Like Australopith from South Africa. Science, 328(5975), 195\u2013204." },
  { id: "23", text: "Dunbar, R.I.M. (1998). The social brain hypothesis. Evolutionary Anthropology, 6(5), 178\u2013190." },
] as const;
