export const IMAGES = {
  skeletalSpecimens: "https://images.esy.com/essays/homo-naledi/homo-naledi-skeletal-specimens.1151e1c05c.webp",
  facialReconstruction: "https://images.esy.com/essays/homo-naledi/homo-naledi-facial-reconstruction.e82db47297.webp",
  facialReconstructionMUSE: "https://images.esy.com/essays/homo-naledi/homo-naledi-facial-reconstruction.7bd790d0fe.webp",
  caveExploration: "https://images.esy.com/essays/homo-naledi/rising-star-cave-exploration-14054047275.c5dc94263c.webp",
  caveCrossSection: "https://images.esy.com/essays/homo-naledi/cross-section-of-the-rising-star-cave-system-dinaledi-chamber.9c609c8eba.svg",
  caveSystemMap: "https://images.esy.com/essays/homo-naledi/rising-star-cave-system-marking-the-dinaledi-and-lesedi-chambers.d6b7ed9fcc.webp",
  handDorsal: "https://images.esy.com/essays/homo-naledi/homo-naledi-right-hand-dorsal.b108f81bc3.webp",
  handComplete: "https://images.esy.com/essays/homo-naledi/homo-naledi-hand-1-adult-right-hand.bac94bc093.webp",
  handWristBones: "https://images.esy.com/essays/homo-naledi/homo-naledi-hand-1-wrist-bones.a4f02e0ae5.webp",
  handMetacarpals: "https://images.esy.com/essays/homo-naledi/homo-naledi-metacarpals.9ce64c65b5.webp",
  handPollicalMc1: "https://images.esy.com/essays/homo-naledi/homo-naledi-pollical-metacarpal-mc1-morphology.9a16009914.webp",
  phalangealCurvature: "https://images.esy.com/essays/homo-naledi/phalangeal-curvature-in-homo-naledi.1a9e06f0ce.webp",
  foot: "https://images.esy.com/essays/homo-naledi/homo-naledi-foot.643a772bad.webp",
  footAdultRight: "https://images.esy.com/essays/homo-naledi/homo-naledi-foot-adult-right.dab5330a03.webp",
  footDigitalReconstruction: "https://images.esy.com/essays/homo-naledi/digital-reconstruction-of-the-foot-of-homo-naledi.5016a0bd25.webp",
  tali: "https://images.esy.com/essays/homo-naledi/homo-naledi-tali-from-dinaledi-chamber.38d0ba4b93.webp",
  mandible: "https://images.esy.com/essays/homo-naledi/homo-naledi-mandible-2.487895c853.webp",
  dentalComparison: "https://images.esy.com/essays/homo-naledi/elife-24232-fig10-v1-mandibular-and-dental-anatomy-in-homo-naledi-compared-to-other-species-of-homo.2695448ed2.webp",
  dh7Skull: "https://images.esy.com/essays/homo-naledi/dh7-homo-naledi.41469bc4be.webp",
  secondMetacarpal: "https://images.esy.com/essays/homo-naledi/homo-naledi-second-metacarpal-uw-101-1474.57a8bbbf42.webp",
  museumReconstruction: "https://images.esy.com/essays/homo-naledi/em-homo-naledi-1.ee6042e914.webp",
  marinaElliott: "https://images.esy.com/essays/homo-naledi/marina-elliott.80aa5296bb.webp",
  beccaPeixotto: "https://images.esy.com/essays/homo-naledi/becca-peixotto.01e61a8e16.webp",
  peixottoAndElliott: "https://images.esy.com/essays/homo-naledi/becca-peixotto-and-marina-elliott-14050842062.7a8cd4a2a0.webp",
  gautengMap: "https://images.esy.com/essays/homo-naledi/south-africa-gauteng-location-map.082a596cf3.svg",
  handNonPollicalMc: "https://images.esy.com/essays/homo-naledi/homo-naledi-hand-1-non-pollical-metacarpals.7e119b2bba.webp",
} as const;

export const IMAGE_CREDITS = [
  { subject: "Homo naledi skeletal specimens from Dinaledi Chamber", attribution: "Berger et al. 2015, eLife (CC-BY 4.0)", url: "https://commons.wikimedia.org/wiki/File:Homo_naledi_skeletal_specimens.jpg" },
  { subject: "Homo naledi facial reconstruction (coherent anatomical deformation)", attribution: "Cicero Moraes, CC-BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Homo_naledi_facial_reconstruction.jpg" },
  { subject: "Homo naledi facial reconstruction (MUSE museum)", attribution: "Matteo De Stefano/MUSE, CC-BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:Homo_Naledi_-_Facial_reconstruction.jpg" },
  { subject: "Rising Star cave exploration", attribution: "Wits University/Berger, CC-BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Rising_star_cave_exploration_(14054047275).jpg" },
  { subject: "Cross-section of Rising Star Cave system and Dinaledi Chamber", attribution: "Paul H.G.M. Dirks et al. 2015, eLife (CC-BY 4.0)", url: "https://commons.wikimedia.org/wiki/File:Cross-section_of_the_Rising_Star_Cave_system_Dinaledi_Chamber.svg" },
  { subject: "Rising Star Cave system showing Dinaledi and Lesedi Chambers", attribution: "Hawks et al. 2017, eLife (CC-BY 4.0)", url: "https://commons.wikimedia.org/wiki/File:Rising_Star_Cave_system_marking_the_Dinaledi_and_Lesedi_Chambers.jpg" },
  { subject: "Homo naledi right hand, dorsal view", attribution: "Kivell et al. 2015, Nature Communications (CC-BY 4.0)", url: "https://commons.wikimedia.org/wiki/File:Homo_naledi_right_hand_dorsal.jpg" },
  { subject: "Homo naledi Hand 1, complete adult right hand", attribution: "Kivell et al. 2015, Nature Communications (CC-BY 4.0)", url: "https://commons.wikimedia.org/wiki/File:Homo_naledi_Hand_1_adult_right_hand.jpg" },
  { subject: "Homo naledi Hand 1 wrist bones", attribution: "Kivell et al. 2015, Nature Communications (CC-BY 4.0)", url: "https://commons.wikimedia.org/wiki/File:Homo_naledi_Hand_1_wrist_bones.jpg" },
  { subject: "Homo naledi first metacarpals", attribution: "Kivell et al. 2015, Nature Communications (CC-BY 4.0)", url: "https://commons.wikimedia.org/wiki/File:Homo_naledi_metacarpals.jpg" },
  { subject: "Homo naledi pollical metacarpal (Mc1) morphology", attribution: "Kivell et al. 2015, Nature Communications (CC-BY 4.0)", url: "https://commons.wikimedia.org/wiki/File:Homo_naledi_pollical_metacarpal_(Mc1)_morphology.jpg" },
  { subject: "Phalangeal curvature in Homo naledi", attribution: "Kivell et al. 2015, Nature Communications (CC-BY 4.0)", url: "https://commons.wikimedia.org/wiki/File:Phalangeal_curvature_in_Homo_naledi.jpg" },
  { subject: "Homo naledi foot composite", attribution: "Harcourt-Smith et al. 2015, Nature Communications (CC-BY 4.0)", url: "https://commons.wikimedia.org/wiki/File:Homo_naledi_foot.jpg" },
  { subject: "Homo naledi adult right foot", attribution: "Harcourt-Smith et al. 2015, Nature Communications (CC-BY 4.0)", url: "https://commons.wikimedia.org/wiki/File:Homo_naledi_foot-_adult_right.jpg" },
  { subject: "Digital reconstruction of Homo naledi foot", attribution: "Harcourt-Smith et al. 2015, Nature Communications (CC-BY 4.0)", url: "https://commons.wikimedia.org/wiki/File:Digital_reconstruction_of_the_foot_of_Homo_naledi.jpg" },
  { subject: "Homo naledi tali from Dinaledi Chamber", attribution: "Harcourt-Smith et al. 2015, Nature Communications (CC-BY 4.0)", url: "https://commons.wikimedia.org/wiki/File:Homo_naledi_tali_from_Dinaledi_Chamber.jpg" },
  { subject: "Homo naledi mandible shortly after recovery", attribution: "Lee R. Berger, eLife (CC-BY 4.0)", url: "https://commons.wikimedia.org/wiki/File:Homo_naledi_mandible_2.jpg" },
  { subject: "Mandibular and dental anatomy comparison across Homo species", attribution: "Hawks et al. 2017, eLife (CC-BY 4.0)", url: "https://commons.wikimedia.org/wiki/File:Elife-24232-fig10-v1_Mandibular_and_dental_anatomy_in_Homo_naledi_compared_to_other_species_of_Homo.jpg" },
  { subject: "DH7 Homo naledi cranium", attribution: "Berger et al. 2015, eLife (CC-BY 4.0)", url: "https://commons.wikimedia.org/wiki/File:DH7_Homo_naledi.png" },
  { subject: "Homo naledi second metacarpal UW 101-1474", attribution: "Kivell et al. 2015, Nature Communications (CC-BY 4.0)", url: "https://commons.wikimedia.org/wiki/File:Homo_naledi_second_metacarpal_UW_101-1474.jpg" },
  { subject: "Homo naledi museum reconstruction (Trento Science Museum)", attribution: "Sailko, CC-BY 3.0", url: "https://commons.wikimedia.org/wiki/File:Em_-_Homo_naledi_-_1.jpg" },
  { subject: "Marina Elliott, underground astronaut and paleoanthropologist", attribution: "Marina Elliott, CC-BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Marina_Elliott.jpg" },
  { subject: "Becca Peixotto, underground astronaut", attribution: "Becca Peixotto, CC-BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Becca_Peixotto.png" },
  { subject: "Becca Peixotto and Marina Elliott during Rising Star expedition", attribution: "Wits University/Berger, CC-BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Becca_Peixotto_and_Marina_Elliott_(14050842062).jpg" },
  { subject: "Mrs Ples (Sts 5) Australopithecus africanus skull", attribution: "Didier Descouens, CC-BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Mrs_Ples.jpg" },
  { subject: "South Africa Gauteng province location map", attribution: "NordNordWest, CC-BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:South_Africa_Gauteng_location_map.svg" },
  { subject: "Homo naledi Hand 1 non-pollical metacarpals", attribution: "Kivell et al. 2015, Nature Communications (CC-BY 4.0)", url: "https://commons.wikimedia.org/wiki/File:Homo_naledi_Hand_1_non-pollical_metacarpals.jpg" },
] as const;

export const SOURCES = [
  { id: "1", text: "Berger, L.R. et al. (2015). Homo naledi, a new species of the genus Homo from the Dinaledi Chamber, South Africa. eLife, 4:e09560." },
  { id: "2", text: "Dirks, P.H.G.M. et al. (2015). Geological and taphonomic context for the new hominin species Homo naledi from the Dinaledi Chamber, South Africa. eLife, 4:e09561." },
  { id: "3", text: "Hawks, J. et al. (2017). New fossil remains of Homo naledi from the Lesedi Chamber, South Africa. eLife, 6:e24232." },
  { id: "4", text: "Dirks, P.H.G.M. et al. (2017). The age of Homo naledi and associated sediments in the Rising Star Cave, South Africa. eLife, 6:e24231." },
  { id: "5", text: "Kivell, T.L. et al. (2015). The hand of Homo naledi. Nature Communications, 6:8431." },
  { id: "6", text: "Harcourt-Smith, W.E.H. et al. (2015). The foot of Homo naledi. Nature Communications, 6:8432." },
  { id: "7", text: "Garvin, H.M. et al. (2017). Body size, brain size, and sexual dimorphism in Homo naledi from the Dinaledi Chamber. Journal of Human Evolution, 111, 119\u2013138." },
  { id: "8", text: "Val, A. (2016). Deliberate body disposal by hominins in the Dinaledi Chamber, Cradle of Humankind, South Africa? Journal of Human Evolution, 96, 145\u2013148." },
  { id: "9", text: "Thackeray, J.F. (2016). The possibility of lichen growth on bones of Homo naledi: Were they exposed to light? South African Journal of Science, 112(7/8)." },
  { id: "10", text: "Berger, L.R. et al. (2023). Evidence for deliberate burial of the dead by Homo naledi. eLife, 12:RP89106." },
  { id: "11", text: "Martin\u00f3n-Torres, M. et al. (2015). Dental morphology of Homo naledi. Nature Communications, 6:8431." },
  { id: "12", text: "Williams, S.A. et al. (2017). The vertebrae and ribs of Homo naledi. Journal of Human Evolution, 104, 136\u2013154." },
  { id: "13", text: "Dembo, M. et al. (2016). The evolutionary relationships and age of Homo naledi: An assessment using dated Bayesian phylogenetic methods. Journal of Human Evolution, 97, 17\u201326." },
  { id: "14", text: "Elliott, M.C. et al. (2021). Underground astronauts: The excavation methodology of the Rising Star Cave system. South African Archaeological Bulletin, 76(215), 115\u2013128." },
  { id: "15", text: "Shreeve, J. (2015). Mystery of the New Human Species. National Geographic, 228(4), 30\u201357." },
  { id: "16", text: "Holloway, R.L. et al. (2018). Endocast morphology of Homo naledi from the Dinaledi Chamber, South Africa. Proceedings of the National Academy of Sciences, 115(22), 5738\u20135743." },
  { id: "17", text: "Feuerriegel, E.M. et al. (2017). The upper limb of Homo naledi. Journal of Human Evolution, 104, 155\u2013173." },
  { id: "18", text: "Marchi, D. et al. (2017). The thigh and leg of Homo naledi. Journal of Human Evolution, 104, 174\u2013204." },
  { id: "19", text: "VanSickle, C. et al. (2017). Homo naledi pelvic remains from the Dinaledi Chamber, South Africa. Journal of Human Evolution, 104, 185\u2013206." },
  { id: "20", text: "Laird, M.F. et al. (2017). The skull of Homo naledi. Journal of Human Evolution, 104, 100\u2013123." },
  { id: "21", text: "Schroeder, L. et al. (2017). Skull diversity in the Homo lineage and the relative position of Homo naledi. Journal of Human Evolution, 104, 124\u2013135." },
  { id: "22", text: "Cofran, Z. & Walker, C.S. (2017). Dental development in Homo naledi. Journal of Human Evolution, 104, 34\u201344." },
  { id: "23", text: "Zipfel, B. et al. (2017). The foot and ankle of Homo naledi from the Dinaledi Chamber, South Africa. Journal of Human Evolution, 104, 155\u2013173." },
  { id: "24", text: "Wood, B. & Boyle, E.K. (2016). Hominin taxic diversity: Fact or fantasy? American Journal of Physical Anthropology, 159(S61), 37\u201378." },
] as const;
