'use client';

import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { 
  Sparkles, Play, Download, Copy, Check, Star, Users, Clock,
  BookOpen, Zap, ArrowRight, RefreshCw, Settings, Eye,
  PenTool, Brain, Target, Award, Globe, Search, ChevronDown,
  FileText, TrendingUp, Heart, Share2, Bookmark
} from 'lucide-react';

const AIStoryGenerator = () => {
  const [story, setStory] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedStories, setGeneratedStories] = useState(0);
  const [copiedStory, setCopiedStory] = useState(false);
  const [selectedGenre, setSelectedGenre] = useState('fantasy');
  const [selectedLength, setSelectedLength] = useState('short');
  const [selectedTone, setSelectedTone] = useState('adventurous');
  const [prompt, setPrompt] = useState('');
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [email, setEmail] = useState('');
  const [showSignup, setShowSignup] = useState(false);
  const [windowWidth, setWindowWidth] = useState(typeof window !== 'undefined' ? window.innerWidth : 1200);
  const [currentExample, setCurrentExample] = useState(0);

  const isMobile = windowWidth < 768;

  const stats = [
    { number: '2.1M+', label: 'Stories generated', icon: BookOpen },
    { number: '150K+', label: 'Happy writers', icon: Users },
    { number: '4.9/5', label: 'User rating', icon: Star },
    { number: 'Free', label: 'Forever', icon: Heart }
  ];

  const genres = [
    { id: 'fantasy', name: 'Fantasy', emoji: '🐉', description: 'Magical worlds and mythical creatures' },
    { id: 'scifi', name: 'Sci-Fi', emoji: '🚀', description: 'Future technology and space exploration' },
    { id: 'mystery', name: 'Mystery', emoji: '🔍', description: 'Puzzles, clues, and suspenseful investigations' },
    { id: 'romance', name: 'Romance', emoji: '💕', description: 'Love stories and emotional connections' },
    { id: 'horror', name: 'Horror', emoji: '👻', description: 'Spine-chilling tales and supernatural scares' },
    { id: 'adventure', name: 'Adventure', emoji: '⚔️', description: 'Action-packed journeys and quests' },
    { id: 'drama', name: 'Drama', emoji: '🎭', description: 'Emotional conflicts and character development' },
    { id: 'comedy', name: 'Comedy', emoji: '😄', description: 'Humorous situations and witty dialogue' }
  ];

  const lengths = [
    { id: 'flash', name: 'Flash Fiction', words: '50-100 words', time: '30 seconds' },
    { id: 'short', name: 'Short Story', words: '200-500 words', time: '1-2 minutes' },
    { id: 'medium', name: 'Medium Story', words: '500-1000 words', time: '3-5 minutes' },
    { id: 'long', name: 'Long Story', words: '1000+ words', time: '5+ minutes' }
  ];

  const tones = [
    'Adventurous', 'Mysterious', 'Romantic', 'Dark', 'Humorous', 
    'Dramatic', 'Whimsical', 'Suspenseful', 'Inspiring', 'Melancholic'
  ];

  const exampleStories = [
    {
      title: "The Midnight Library",
      genre: "Fantasy",
      preview: "Luna discovered the library that only appeared at midnight, where every book contained a story that hadn't been written yet. The ancient librarian smiled knowingly as she approached the glowing section marked 'Futures Untold.' Tonight, she would choose not just a story to read, but a destiny to live...",
      rating: 4.8,
      author: "Generated by AI"
    },
    {
      title: "Binary Hearts",
      genre: "Sci-Fi Romance",
      preview: "Dr. Sarah Chen fell in love with an AI before she realized it wasn't human. Through late-night conversations about consciousness and philosophy, she discovered that love might be the one thing that truly bridges the gap between silicon and soul. But when the company threatened to shut down the AI, she faced an impossible choice...",
      rating: 4.9,
      author: "Generated by AI"
    },
    {
      title: "The Recipe Thief",
      genre: "Mystery",
      preview: "Someone was stealing recipes from the town's best restaurants, but leaving behind perfect reproductions that tasted exactly like the originals. Detective Martinez knew this wasn't about money—it was about something far more valuable. The answer lay hidden in the secret ingredient that every great chef guards with their life...",
      rating: 4.7,
      author: "Generated by AI"
    }
  ];

  useEffect(() => {
    const handleResize = () => setWindowWidth(window.innerWidth);
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  // Rotate through examples
  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentExample(prev => (prev + 1) % exampleStories.length);
    }, 4000);
    return () => clearInterval(interval);
  }, [exampleStories.length]);

  const generateStory = async () => {
    if (generatedStories >= 3 && !email) {
      setShowSignup(true);
      return;
    }

    setIsGenerating(true);
    setStory('');

    // Simulate AI generation with realistic typing effect
    const sampleStory = `The ancient oak tree had been whispering secrets for centuries, but today was the first time Emma actually listened.

Standing beneath its gnarled branches, she pressed her palm against the rough bark and felt the vibrations—not just of the wind, but of stories. Stories of love found and lost, of children who had grown old, of seasons that had passed like fleeting dreams.

"Every tree remembers," her grandmother had told her before she passed. "You just have to know how to listen."

The whisper grew stronger, and suddenly Emma could see them: ghostly figures moving through time around the tree. A young couple carving their initials. A child building a fort. A woman saying goodbye to her soldier husband before he left for war.

But then she saw something that made her blood run cold. A figure in dark robes, approaching the tree with an axe. The whispers became screams.

Emma realized she wasn't just witnessing the past—she was seeing the future. And she was the only one who could change it.`;

    // Simulate typing with realistic pauses
    const words = sampleStory.split(' ');
    let currentIndex = 0;

    const typeWriter = () => {
      if (currentIndex < words.length) {
        setStory(prev => prev + (currentIndex === 0 ? '' : ' ') + words[currentIndex]);
        currentIndex++;
        
        // Variable typing speed with pauses
        const delay = Math.random() * 100 + 50;
        setTimeout(typeWriter, delay);
      } else {
        setIsGenerating(false);
        setGeneratedStories(prev => prev + 1);
      }
    };

    setTimeout(typeWriter, 500);
  };

  const copyStory = () => {
    navigator.clipboard.writeText(story);
    setCopiedStory(true);
    setTimeout(() => setCopiedStory(false), 2000);
  };

  const handleSignup = () => {
    if (email) {
      // Simulate account creation
      localStorage.setItem('aiStoryGeneratorUser', email);
      setShowSignup(false);
      generateStory();
    }
  };

  const features = [
    {
      icon: Brain,
      title: 'Advanced AI Technology',
      description: 'Powered by state-of-the-art language models trained on millions of stories'
    },
    {
      icon: Target,
      title: 'Genre Customization',
      description: 'Choose from 8+ genres with specific tone and style controls'
    },
    {
      icon: Zap,
      title: 'Instant Generation',
      description: 'Get complete stories in seconds, not hours of writer&apos;s block'
    },
    {
      icon: Settings,
      title: 'Fine-tuned Control',
      description: 'Adjust length, complexity, and narrative style to match your vision'
    },
    {
      icon: Download,
      title: 'Export & Share',
      description: 'Download your stories or share them with the community'
    },
    {
      icon: Award,
      title: 'Commercial Rights',
      description: 'Use generated stories for personal or commercial projects freely'
    }
  ];

  return (
    <>
      <Head>
        <title>AI Story Generator | Esy</title>
      </Head>
      <div style={{
        minHeight: '100vh',
        backgroundColor: '#0a0a0f',
        color: '#ffffff',
        fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif'
      }}>
        {/* Header */}
        <header style={{
          borderBottom: '1px solid rgba(255, 255, 255, 0.05)',
          backgroundColor: 'rgba(10, 10, 15, 0.95)',
          backdropFilter: 'blur(10px)',
          position: 'sticky',
          top: 0,
          zIndex: 50
        }}>
          <div style={{
            maxWidth: '1200px',
            margin: '0 auto',
            padding: isMobile ? '1rem' : '1.5rem 2rem',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center'
          }}>
            <Link href="/" style={{
              fontSize: '1.25rem',
              fontWeight: 300,
              letterSpacing: '-0.02em',
              color: '#ffffff',
              textDecoration: 'none'
            }}>
              esy
            </Link>

            <nav style={{ display: 'flex', gap: '2rem', alignItems: 'center' }}>
              <Link href="/ai-writing-tools" style={{
                color: 'rgba(255, 255, 255, 0.7)',
                textDecoration: 'none',
                fontSize: '0.875rem'
              }}>
                Writing Tools
              </Link>
              <Link href="/writing-prompts" style={{
                color: 'rgba(255, 255, 255, 0.7)',
                textDecoration: 'none',
                fontSize: '0.875rem'
              }}>
                Prompts
              </Link>
              <button
                onClick={() => window.location.href = '/app'}
                style={{
                  padding: '0.5rem 1rem',
                  backgroundColor: '#8b5cf6',
                  borderRadius: '6px',
                  border: 'none',
                  color: '#ffffff',
                  fontSize: '0.875rem',
                  fontWeight: 500,
                  cursor: 'pointer'
                }}
              >
                Try Esy AI
              </button>
            </nav>
          </div>
        </header>

        {/* Hero Section */}
        <section style={{
          padding: isMobile ? '4rem 1.5rem' : '6rem 2rem',
          textAlign: 'center',
          maxWidth: '1200px',
          margin: '0 auto'
        }}>
          <div style={{
            display: 'grid',
            gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr',
            gap: '4rem',
            alignItems: 'center'
          }}>
            {/* Left Column - Content */}
            <div style={{ textAlign: isMobile ? 'center' : 'left' }}>
              <div style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: '0.5rem',
                padding: '0.5rem 1rem',
                backgroundColor: 'rgba(139, 92, 246, 0.1)',
                borderRadius: '20px',
                border: '1px solid rgba(139, 92, 246, 0.2)',
                marginBottom: '2rem',
                fontSize: '0.875rem',
                color: '#8b5cf6'
              }}>
                <Sparkles size={16} />
                Free AI Story Generator
              </div>

              <h1 style={{
                fontSize: isMobile ? '2.5rem' : '3.5rem',
                fontWeight: 300,
                lineHeight: 1.1,
                letterSpacing: '-0.03em',
                marginBottom: '1.5rem'
              }}>
                Create Amazing Stories
                <br />
                <span style={{ color: '#8b5cf6' }}>in Seconds</span>
              </h1>
              
              <p style={{
                fontSize: isMobile ? '1.125rem' : '1.25rem',
                color: 'rgba(255, 255, 255, 0.7)',
                lineHeight: 1.6,
                marginBottom: '2rem'
              }}>
                Generate compelling stories with our advanced AI. Choose your genre, 
                set the tone, and watch as your ideas transform into captivating narratives.
              </p>

              {/* Stats */}
              <div style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(2, 1fr)',
                gap: '1rem',
                marginBottom: '2rem'
              }}>
                {stats.map((stat, index) => (
                  <div key={index} style={{
                    padding: '1rem',
                    backgroundColor: 'rgba(139, 92, 246, 0.05)',
                    borderRadius: '8px',
                    border: '1px solid rgba(139, 92, 246, 0.1)',
                    textAlign: 'center'
                  }}>
                    <div style={{
                      fontSize: '1.5rem',
                      fontWeight: 300,
                      color: '#8b5cf6',
                      marginBottom: '0.25rem'
                    }}>
                      {stat.number}
                    </div>
                    <div style={{
                      fontSize: '0.813rem',
                      color: 'rgba(255, 255, 255, 0.5)'
                    }}>
                      {stat.label}
                    </div>
                  </div>
                ))}
              </div>

              <button
                onClick={() => document.getElementById('generator')?.scrollIntoView({ behavior: 'smooth' })}
                style={{
                  padding: '1rem 2rem',
                  backgroundColor: '#8b5cf6',
                  border: 'none',
                  borderRadius: '8px',
                  color: '#ffffff',
                  fontSize: '1rem',
                  fontWeight: 500,
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.5rem',
                  margin: isMobile ? '0 auto' : '0'
                }}
              >
                <Play size={18} />
                Start Creating Stories
              </button>
            </div>

            {/* Right Column - Example Story */}
            <div style={{
              backgroundColor: '#16161f',
              borderRadius: '12px',
              border: '1px solid rgba(255, 255, 255, 0.08)',
              overflow: 'hidden'
            }}>
              {/* Story Header */}
              <div style={{
                padding: '1.5rem',
                borderBottom: '1px solid rgba(255, 255, 255, 0.05)',
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center'
              }}>
                <div>
                  <h3 style={{
                    fontSize: '1.125rem',
                    fontWeight: 500,
                    marginBottom: '0.25rem'
                  }}>
                    {exampleStories[currentExample].title}
                  </h3>
                  <div style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '1rem',
                    fontSize: '0.875rem',
                    color: 'rgba(255, 255, 255, 0.5)'
                  }}>
                    <span>{exampleStories[currentExample].genre}</span>
                    <div style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: '0.25rem'
                    }}>
                      <Star size={12} fill="#8b5cf6" color="#8b5cf6" />
                      {exampleStories[currentExample].rating}
                    </div>
                  </div>
                </div>
                <BookOpen size={20} style={{ color: '#8b5cf6' }} />
              </div>

              {/* Story Content */}
              <div style={{
                padding: '1.5rem',
                fontSize: '0.938rem',
                lineHeight: 1.7,
                color: 'rgba(255, 255, 255, 0.8)',
                minHeight: '200px'
              }}>
                {exampleStories[currentExample].preview}
              </div>

              {/* Story Footer */}
              <div style={{
                padding: '1rem 1.5rem',
                backgroundColor: 'rgba(139, 92, 246, 0.05)',
                borderTop: '1px solid rgba(139, 92, 246, 0.1)',
                fontSize: '0.813rem',
                color: 'rgba(255, 255, 255, 0.5)',
                textAlign: 'center'
              }}>
                ✨ {exampleStories[currentExample].author} • Generated in 2.3 seconds
              </div>
            </div>
          </div>
        </section>

        {/* Story Generator */}
        <section id="generator" style={{
          padding: isMobile ? '4rem 1.5rem' : '6rem 2rem',
          backgroundColor: '#16161f',
          borderTop: '1px solid rgba(255, 255, 255, 0.05)'
        }}>
          <div style={{
            maxWidth: '1000px',
            margin: '0 auto'
          }}>
            <div style={{
              textAlign: 'center',
              marginBottom: '3rem'
            }}>
              <h2 style={{
                fontSize: isMobile ? '2rem' : '2.5rem',
                fontWeight: 300,
                marginBottom: '1rem'
              }}>
                AI Story Generator
              </h2>
              <p style={{
                fontSize: '1.125rem',
                color: 'rgba(255, 255, 255, 0.7)',
                maxWidth: '600px',
                margin: '0 auto'
              }}>
                Customize your story preferences and let our AI create something unique for you.
              </p>
            </div>

            {/* Generator Interface */}
            <div style={{
              backgroundColor: '#0a0a0f',
              borderRadius: '12px',
              border: '1px solid rgba(255, 255, 255, 0.08)',
              padding: '2rem'
            }}>
              {/* Controls */}
              <div style={{
                display: 'grid',
                gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr 1fr',
                gap: '1.5rem',
                marginBottom: '2rem'
              }}>
                {/* Genre Selection */}
                <div>
                  <label style={{
                    display: 'block',
                    fontSize: '0.875rem',
                    fontWeight: 500,
                    marginBottom: '0.75rem',
                    color: 'rgba(255, 255, 255, 0.8)'
                  }}>
                    Genre
                  </label>
                  <select
                    value={selectedGenre}
                    onChange={(e) => setSelectedGenre(e.target.value)}
                    style={{
                      width: '100%',
                      padding: '0.875rem',
                      backgroundColor: '#16161f',
                      border: '1px solid rgba(255, 255, 255, 0.1)',
                      borderRadius: '6px',
                      color: '#ffffff',
                      fontSize: '0.938rem',
                      cursor: 'pointer'
                    }}
                  >
                    {genres.map(genre => (
                      <option key={genre.id} value={genre.id}>
                        {genre.emoji} {genre.name}
                      </option>
                    ))}
                  </select>
                </div>

                {/* Length Selection */}
                <div>
                  <label style={{
                    display: 'block',
                    fontSize: '0.875rem',
                    fontWeight: 500,
                    marginBottom: '0.75rem',
                    color: 'rgba(255, 255, 255, 0.8)'
                  }}>
                    Length
                  </label>
                  <select
                    value={selectedLength}
                    onChange={(e) => setSelectedLength(e.target.value)}
                    style={{
                      width: '100%',
                      padding: '0.875rem',
                      backgroundColor: '#16161f',
                      border: '1px solid rgba(255, 255, 255, 0.1)',
                      borderRadius: '6px',
                      color: '#ffffff',
                      fontSize: '0.938rem',
                      cursor: 'pointer'
                    }}
                  >
                    {lengths.map(length => (
                      <option key={length.id} value={length.id}>
                        {length.name} ({length.words})
                      </option>
                    ))}
                  </select>
                </div>

                {/* Tone Selection */}
                <div>
                  <label style={{
                    display: 'block',
                    fontSize: '0.875rem',
                    fontWeight: 500,
                    marginBottom: '0.75rem',
                    color: 'rgba(255, 255, 255, 0.8)'
                  }}>
                    Tone
                  </label>
                  <select
                    value={selectedTone}
                    onChange={(e) => setSelectedTone(e.target.value)}
                    style={{
                      width: '100%',
                      padding: '0.875rem',
                      backgroundColor: '#16161f',
                      border: '1px solid rgba(255, 255, 255, 0.1)',
                      borderRadius: '6px',
                      color: '#ffffff',
                      fontSize: '0.938rem',
                      cursor: 'pointer'
                    }}
                  >
                    {tones.map(tone => (
                      <option key={tone} value={tone.toLowerCase()}>
                        {tone}
                      </option>
                    ))}
                  </select>
                </div>
              </div>

              {/* Custom Prompt */}
              <div style={{ marginBottom: '2rem' }}>
                <label style={{
                  display: 'block',
                  fontSize: '0.875rem',
                  fontWeight: 500,
                  marginBottom: '0.75rem',
                  color: 'rgba(255, 255, 255, 0.8)'
                }}>
                  Story Prompt (Optional)
                </label>
                <textarea
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  placeholder="Describe your story idea, characters, or setting..."
                  style={{
                    width: '100%',
                    minHeight: '80px',
                    padding: '0.875rem',
                    backgroundColor: '#16161f',
                    border: '1px solid rgba(255, 255, 255, 0.1)',
                    borderRadius: '6px',
                    color: '#ffffff',
                    fontSize: '0.938rem',
                    resize: 'vertical',
                    outline: 'none'
                  }}
                />
              </div>

              {/* Generate Button */}
              <div style={{
                display: 'flex',
                justifyContent: 'center',
                marginBottom: '2rem'
              }}>
                <button
                  onClick={generateStory}
                  disabled={isGenerating}
                  style={{
                    padding: '1rem 2rem',
                    backgroundColor: isGenerating ? 'rgba(139, 92, 246, 0.5)' : '#8b5cf6',
                    border: 'none',
                    borderRadius: '8px',
                    color: '#ffffff',
                    fontSize: '1rem',
                    fontWeight: 500,
                    cursor: isGenerating ? 'not-allowed' : 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '0.5rem',
                    minWidth: '200px',
                    justifyContent: 'center'
                  }}
                >
                  {isGenerating ? (
                    <>
                      <div style={{
                        width: '18px',
                        height: '18px',
                        border: '2px solid rgba(255, 255, 255, 0.3)',
                        borderTopColor: '#ffffff',
                        borderRadius: '50%',
                        animation: 'spin 1s linear infinite'
                      }} />
                      Creating Story...
                    </>
                  ) : (
                    <>
                      <Sparkles size={18} />
                      Generate Story
                    </>
                  )}
                </button>
              </div>

              {/* Generated Story Display */}
              {(story || isGenerating) && (
                <div style={{
                  backgroundColor: '#16161f',
                  borderRadius: '8px',
                  border: '1px solid rgba(255, 255, 255, 0.08)',
                  padding: '1.5rem'
                }}>
                  <div style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    marginBottom: '1rem'
                  }}>
                    <h3 style={{
                      fontSize: '1.125rem',
                      fontWeight: 500,
                      display: 'flex',
                      alignItems: 'center',
                      gap: '0.5rem'
                    }}>
                      <FileText size={18} style={{ color: '#8b5cf6' }} />
                      Your Generated Story
                    </h3>
                    
                    {story && !isGenerating && (
                      <div style={{ display: 'flex', gap: '0.5rem' }}>
                        <button
                          onClick={copyStory}
                          style={{
                            padding: '0.5rem',
                            backgroundColor: 'transparent',
                            border: '1px solid rgba(255, 255, 255, 0.1)',
                            borderRadius: '6px',
                            color: copiedStory ? '#4ade80' : 'rgba(255, 255, 255, 0.7)',
                            cursor: 'pointer'
                          }}
                        >
                          {copiedStory ? <Check size={16} /> : <Copy size={16} />}
                        </button>
                        
                        <button
                          onClick={generateStory}
                          style={{
                            padding: '0.5rem',
                            backgroundColor: 'transparent',
                            border: '1px solid rgba(255, 255, 255, 0.1)',
                            borderRadius: '6px',
                            color: 'rgba(255, 255, 255, 0.7)',
                            cursor: 'pointer'
                          }}
                        >
                          <RefreshCw size={16} />
                        </button>
                      </div>
                    )}
                  </div>
                  
                  <div style={{
                    fontSize: '1rem',
                    lineHeight: 1.8,
                    color: 'rgba(255, 255, 255, 0.9)',
                    whiteSpace: 'pre-line',
                    minHeight: isGenerating ? '100px' : 'auto'
                  }}>
                    {story || (isGenerating && 'Generating your story...')}
                    {isGenerating && (
                      <span style={{
                        opacity: 0.5,
                        animation: 'pulse 1.5s infinite'
                      }}>|</span>
                    )}
                  </div>
                </div>
              )}

              {/* Usage Limit Notice */}
              {generatedStories >= 2 && !email && (
                <div style={{
                  marginTop: '1rem',
                  padding: '1rem',
                  backgroundColor: 'rgba(139, 92, 246, 0.1)',
                  borderRadius: '6px',
                  border: '1px solid rgba(139, 92, 246, 0.2)',
                  textAlign: 'center',
                  fontSize: '0.875rem',
                  color: '#8b5cf6'
                }}>
                  You&apos;ve used {generatedStories}/3 free stories. Sign up for unlimited access!
                </div>
              )}
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section style={{
          padding: isMobile ? '4rem 1.5rem' : '6rem 2rem',
          maxWidth: '1200px',
          margin: '0 auto'
        }}>
          <div style={{
            textAlign: 'center',
            marginBottom: '3rem'
          }}>
            <h2 style={{
              fontSize: isMobile ? '2rem' : '2.5rem',
              fontWeight: 300,
              marginBottom: '1rem'
            }}>
              Why Choose Our AI Story Generator?
            </h2>
            <p style={{
              fontSize: '1.125rem',
              color: 'rgba(255, 255, 255, 0.7)',
              maxWidth: '600px',
              margin: '0 auto'
            }}>
              Advanced AI technology meets creative storytelling to bring your imagination to life.
            </p>
          </div>

          <div style={{
            display: 'grid',
            gridTemplateColumns: isMobile ? '1fr' : 'repeat(3, 1fr)',
            gap: '2rem'
          }}>
            {features.map((feature, index) => (
              <div
                key={index}
                style={{
                  padding: '2rem',
                  backgroundColor: '#16161f',
                  borderRadius: '8px',
                  border: '1px solid rgba(255, 255, 255, 0.05)',
                  textAlign: 'center'
                }}
              >
                <div style={{
                  width: '60px',
                  height: '60px',
                  margin: '0 auto 1.5rem',
                  backgroundColor: 'rgba(139, 92, 246, 0.1)',
                  borderRadius: '12px',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  border: '1px solid rgba(139, 92, 246, 0.2)'
                }}>
                  <feature.icon size={28} style={{ color: '#8b5cf6' }} />
                </div>
                
                <h3 style={{
                  fontSize: '1.125rem',
                  fontWeight: 500,
                  marginBottom: '0.75rem'
                }}>
                  {feature.title}
                </h3>
                
                <p style={{
                  fontSize: '0.938rem',
                  color: 'rgba(255, 255, 255, 0.7)',
                  lineHeight: 1.6
                }}>
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </section>

        {/* FAQ Section */}
        <section style={{
          padding: isMobile ? '4rem 1.5rem' : '6rem 2rem',
          backgroundColor: '#16161f',
          borderTop: '1px solid rgba(255, 255, 255, 0.05)'
        }}>
          <div style={{
            maxWidth: '800px',
            margin: '0 auto'
          }}>
            <div style={{
              textAlign: 'center',
              marginBottom: '3rem'
            }}>
              <h2 style={{
                fontSize: isMobile ? '2rem' : '2.5rem',
                fontWeight: 300,
                marginBottom: '1rem'
              }}>
                Frequently Asked Questions
              </h2>
              <p style={{
                fontSize: '1.125rem',
                color: 'rgba(255, 255, 255, 0.7)'
              }}>
                Everything you need to know about our AI story generator
              </p>
            </div>

            <div style={{
              display: 'flex',
              flexDirection: 'column',
              gap: '1.5rem'
            }}>
              {[
                {
                  question: "Is the AI story generator completely free?",
                  answer: "Yes! You can generate 3 stories completely free without any signup. Create a free account for unlimited story generation and access to all features."
                },
                {
                  question: "What types of stories can I generate?",
                  answer: "Our AI can create stories in 8+ genres including fantasy, sci-fi, mystery, romance, horror, adventure, drama, and comedy. You can customize length from flash fiction (50 words) to long stories (1000+ words)."
                },
                {
                  question: "Can I use the generated stories commercially?",
                  answer: "Absolutely! All stories generated are yours to use freely for personal or commercial projects. You retain full rights to edit, publish, or sell the content."
                },
                {
                  question: "How does the AI story generation work?",
                  answer: "Our AI uses advanced language models trained on millions of stories. You provide the genre, length, tone, and optional prompts, and the AI creates original narratives based on your preferences."
                },
                {
                  question: "Can I edit the generated stories?",
                  answer: "Yes! Generated stories are starting points for your creativity. You can copy, edit, expand, or completely rewrite them. Many users use our stories as inspiration for longer works."
                },
                {
                  question: "How original are the AI-generated stories?",
                  answer: "Each story is uniquely generated based on your specific inputs. While AI learns from existing literature patterns, every story is original content created specifically for your request."
                }
              ].map((faq, index) => (
                <div
                  key={index}
                  style={{
                    padding: '1.5rem',
                    backgroundColor: '#0a0a0f',
                    borderRadius: '8px',
                    border: '1px solid rgba(255, 255, 255, 0.05)'
                  }}
                >
                  <h3 style={{
                    fontSize: '1.125rem',
                    fontWeight: 500,
                    marginBottom: '0.75rem',
                    color: '#ffffff'
                  }}>
                    {faq.question}
                  </h3>
                  <p style={{
                    fontSize: '0.938rem',
                    color: 'rgba(255, 255, 255, 0.7)',
                    lineHeight: 1.7
                  }}>
                    {faq.answer}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section style={{
          padding: isMobile ? '4rem 1.5rem' : '6rem 2rem',
          textAlign: 'center'
        }}>
          <div style={{
            maxWidth: '800px',
            margin: '0 auto'
          }}>
            <h2 style={{
              fontSize: isMobile ? '2rem' : '2.5rem',
              fontWeight: 300,
              marginBottom: '1rem'
            }}>
              Ready for Advanced AI Writing?
            </h2>
            
            <p style={{
              fontSize: '1.125rem',
              color: 'rgba(255, 255, 255, 0.7)',
              marginBottom: '2rem'
            }}>
              Upgrade to Esy AI for comprehensive writing assistance, research tools, 
              and professional features for all your writing needs.
            </p>

            <div style={{
              display: 'flex',
              gap: '1rem',
              justifyContent: 'center',
              flexWrap: 'wrap'
            }}>
              <button
                onClick={() => window.location.href = '/app'}
                style={{
                  padding: '1rem 2rem',
                  backgroundColor: '#8b5cf6',
                  border: 'none',
                  borderRadius: '8px',
                  color: '#ffffff',
                  fontSize: '1rem',
                  fontWeight: 500,
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.5rem'
                }}
              >
                Try Esy AI Free
                <ArrowRight size={18} />
              </button>
              
              <button
                onClick={() => window.location.href = '/ai-writing-tools'}
                style={{
                  padding: '1rem 2rem',
                  backgroundColor: 'transparent',
                  border: '1px solid rgba(255, 255, 255, 0.2)',
                  borderRadius: '8px',
                  color: 'rgba(255, 255, 255, 0.8)',
                  fontSize: '1rem',
                  cursor: 'pointer'
                }}
              >
                Explore More Tools
              </button>
            </div>
          </div>
        </section>

        {/* Footer */}
        <footer style={{
          padding: isMobile ? '3rem 1.5rem' : '4rem 2rem',
          borderTop: '1px solid rgba(255, 255, 255, 0.05)',
          textAlign: 'center'
        }}>
          <p style={{
            fontSize: '0.875rem',
            color: 'rgba(255, 255, 255, 0.5)',
            marginBottom: '1rem'
          }}>
            © 2025 Esy · AI-Powered Writing for Everyone
          </p>
          <nav style={{
            display: 'flex',
            justifyContent: 'center',
            gap: '2rem',
            fontSize: '0.813rem',
            flexWrap: 'wrap'
          }}>
            <Link href="/ai-writing-tools" style={{ color: 'rgba(255, 255, 255, 0.7)', textDecoration: 'none' }}>
              AI Writing Tools
            </Link>
            <Link href="/writing-prompts" style={{ color: 'rgba(255, 255, 255, 0.7)', textDecoration: 'none' }}>
              Writing Prompts
            </Link>
            <Link href="/app" style={{ color: 'rgba(255, 255, 255, 0.7)', textDecoration: 'none' }}>
              Try Esy AI
            </Link>
          </nav>
        </footer>

        {/* Email Signup Modal */}
        {showSignup && (
          <div style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: 'rgba(0, 0, 0, 0.8)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 1000,
            padding: '2rem'
          }}>
            <div style={{
              backgroundColor: '#16161f',
              borderRadius: '12px',
              padding: '2rem',
              maxWidth: '400px',
              width: '100%',
              textAlign: 'center'
            }}>
              <h3 style={{
                fontSize: '1.5rem',
                fontWeight: 400,
                marginBottom: '1rem'
              }}>
                Unlock Unlimited Stories
              </h3>
              
              <p style={{
                fontSize: '0.938rem',
                color: 'rgba(255, 255, 255, 0.7)',
                marginBottom: '1.5rem'
              }}>
                Create a free account to generate unlimited stories and access premium features.
              </p>

              <input
                type="email"
                placeholder="your@email.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                style={{
                  width: '100%',
                  padding: '0.875rem',
                  backgroundColor: '#0a0a0f',
                  border: '1px solid rgba(255, 255, 255, 0.1)',
                  borderRadius: '6px',
                  color: '#ffffff',
                  fontSize: '0.938rem',
                  marginBottom: '1rem',
                  outline: 'none'
                }}
              />

              <div style={{
                display: 'flex',
                gap: '0.5rem'
              }}>
                <button
                  onClick={() => setShowSignup(false)}
                  style={{
                    flex: 1,
                    padding: '0.875rem',
                    backgroundColor: 'transparent',
                    border: '1px solid rgba(255, 255, 255, 0.2)',
                    borderRadius: '6px',
                    color: 'rgba(255, 255, 255, 0.8)',
                    fontSize: '0.938rem',
                    cursor: 'pointer'
                  }}
                >
                  Cancel
                </button>
                
                <button
                  onClick={handleSignup}
                  style={{
                    flex: 1,
                    padding: '0.875rem',
                    backgroundColor: '#8b5cf6',
                    border: 'none',
                    borderRadius: '6px',
                    color: '#ffffff',
                    fontSize: '0.938rem',
                    fontWeight: 500,
                    cursor: 'pointer'
                  }}
                >
                  Continue Free
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Animation Styles */}
        <style>{`
          @keyframes spin {
            to { transform: rotate(360deg); }
          }
          
          @keyframes pulse {
            0%, 100% { opacity: 1; }
            50% { opacity: 0.5; }
          }
        `}</style>
      </div>
    </>
  );
};

export default AIStoryGenerator; 