export const IMAGES = {
  lucy: "https://images.esy.com/essays/lucy/lucy-mexico.44a89c29cc.webp",
  lucySkeleton: "https://images.esy.com/essays/lucy/lucy-skeleton.38b03ca285.webp",
  lucyBlackBg: "https://images.esy.com/essays/lucy/lucy-blackbg.b7ae2af7ed.webp",
  lucyReconstruction: "https://images.esy.com/essays/lucy/lucy-reconstruction.725a4af95a.webp",
  afarensisSkull: "https://images.esy.com/essays/lucy/afarensis-skull-senckenberg.3b58f6a5dd.webp",
  afarensisReconstruction: "https://images.esy.com/essays/lucy/afarensis-reconstruction.e283eae18b.webp",
  laetoliFootprints: "https://images.esy.com/essays/lucy/laetoli-footprints-replica.84894161b9.webp",
  taungChild: "https://images.esy.com/essays/lucy/taung-child.c7202e6439.webp",
  paranthropusBoisei: "https://images.esy.com/essays/lucy/paranthropus-boisei-skull.de00637e03.webp",
  hadar: "https://images.esy.com/essays/lucy/hadar.69dd2d130d.webp",
  afarTriangleMap: "https://images.esy.com/essays/lucy/afar-triangle-political-map.6cd9491dbd.webp",
  afarDepression: "https://images.esy.com/essays/lucy/afar-depression-aster.897b0d84c8.webp",
  dallolLandscape: "https://images.esy.com/essays/lucy/dallol-afar-landscape.a72d4c7aa2.webp",
  afarLakeKarum: "https://images.esy.com/essays/lucy/afar-lake-karum.258cbdbf22.webp",
} as const;

export const IMAGE_CREDITS = [
  { subject: "Lucy skeleton (National Museum, Mexico City)", attribution: "Museo Nacional de Antropolog\u00eda, CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:Lucy_Mexico.jpg" },
  { subject: "Lucy skeleton (articulated)", attribution: "120, CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:Lucy_Skeleton.jpg" },
  { subject: "Lucy skeleton (black background)", attribution: "John Gurche / Cleveland Museum of Natural History, CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:Lucy_blackbg.jpg" },
  { subject: "Lucy reconstruction", attribution: "James St. John, CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Reconstruction_of_the_fossil_skeleton_of_%22Lucy%22_the_Australopithecus_afarensis.jpg" },
  { subject: "A. afarensis skull (Senckenberg Museum)", attribution: "Daderot, CC0 1.0", url: "https://commons.wikimedia.org/wiki/File:Australopithecus_afarensis_skull_-_Naturmuseum_Senckenberg_-_DSC02102.JPG" },
  { subject: "A. afarensis reconstruction", attribution: "Cicero Moraes, CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:Australopithecus_afarensis_reconstruction.JPG" },
  { subject: "Laetoli footprints replica", attribution: "Tim Evanson, CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:Laetoli_footprints_replica.jpg" },
  { subject: "Taung Child skull", attribution: "Didier Descouens, CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Taung_child.jpg" },
  { subject: "Paranthropus boisei skull", attribution: "Nrkpan, CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:Paranthropus_boisei_skull.jpg" },
  { subject: "Hadar, Ethiopia", attribution: "Wikimedia Commons, Public Domain", url: "https://commons.wikimedia.org/wiki/File:Hadar.jpg" },
  { subject: "Afar Triangle political map", attribution: "Sémhur, CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:Afar_Triangle_(political_map).png" },
  { subject: "Afar Depression (ASTER satellite)", attribution: "NASA/GSFC/METI/ERSDAC/JAROS, Public Domain", url: "https://commons.wikimedia.org/wiki/File:Afar_Depression_(ASTER).jpg" },
  { subject: "Dallol landscape, Afar", attribution: "A.Savin, CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:ET_Afar_asv2018-01_img36_Dallol.jpg" },
  { subject: "Lake Karum area, Afar", attribution: "A.Savin, CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:ET_Afar_asv2018-01_img11_Lake_Karum_area.jpg" },
] as const;

export const SOURCES = [
  { id: "1", text: "Johanson, D.C. & White, T.D. (1979). A systematic assessment of early African hominids. Science, 203(4378), 321\u2013330." },
  { id: "2", text: "Johanson, D.C. & Edey, M.A. (1981). Lucy: The Beginnings of Humankind. Simon & Schuster." },
  { id: "3", text: "Kimbel, W.H. & Delezene, L.K. (2009). \u201cLucy\u201d redux: A review of research on Australopithecus afarensis. American Journal of Physical Anthropology, 140(S49), 2\u201348." },
  { id: "4", text: "Kappelman, J. et al. (2016). Perimortem fractures in Lucy suggest mortality from fall out of tall tree. Nature, 537, 503\u2013507." },
  { id: "5", text: "Stern, J.T. Jr. & Susman, R.L. (1983). The locomotor anatomy of Australopithecus afarensis. American Journal of Physical Anthropology, 60(3), 279\u2013317." },
  { id: "6", text: "Lovejoy, C.O. (1988). Evolution of human walking. Scientific American, 259(5), 118\u2013125." },
  { id: "7", text: "Ward, C.V., Kimbel, W.H. & Johanson, D.C. (2011). Complete fourth metatarsal and arches in the foot of Australopithecus afarensis. Science, 331(6018), 750\u2013753." },
  { id: "8", text: "Leakey, M.G. et al. (2001). New hominin genus from eastern Africa shows diverse middle Pliocene lineages. Nature, 410(6827), 433\u2013440." },
  { id: "9", text: "Haile-Selassie, Y. et al. (2015). New species from Ethiopia further expands Middle Pliocene hominin diversity. Nature, 521(7553), 483\u2013488." },
  { id: "10", text: "Wood, B. & Boyle, E.K. (2016). Hominin taxic diversity: Fact or fantasy? American Journal of Physical Anthropology, 159(S61), 37\u201378." },
  { id: "11", text: "Cerling, T.E. et al. (2013). Stable isotope-based diet reconstructions of Turkana Basin hominins. Proceedings of the National Academy of Sciences, 110(26), 10501\u201310506." },
  { id: "12", text: "Reed, K.E. (1997). Early hominid evolution and ecological change through the African Plio-Pleistocene. Journal of Human Evolution, 32(2\u20133), 289\u2013322." },
  { id: "13", text: "Wynn, J.G. et al. (2006). Geological and palaeontological context of a Pliocene juvenile hominin at Dikika, Ethiopia. Nature, 443(7109), 332\u2013336." },
  { id: "14", text: "McHenry, H.M. (1992). Body size and proportions in early hominids. American Journal of Physical Anthropology, 87(4), 407\u2013431." },
  { id: "15", text: "Reno, P.L. et al. (2003). Sexual dimorphism in Australopithecus afarensis was similar to that of modern humans. Proceedings of the National Academy of Sciences, 100(16), 9404\u20139409." },
  { id: "16", text: "Villmoare, B. et al. (2015). Early Homo at 2.8 Ma from Ledi-Geraru, Afar, Ethiopia. Science, 347(6228), 1352\u20131355." },
  { id: "17", text: "Alemseged, Z. et al. (2006). A juvenile early hominin skeleton from Dikika, Ethiopia. Nature, 443(7109), 296\u2013301." },
  { id: "18", text: "Holloway, R.L. et al. (2004). The Human Fossil Record, Volume 3: Brain Endocasts. Wiley-Liss." },
  { id: "19", text: "Dart, R.A. (1925). Australopithecus africanus: The man-ape of South Africa. Nature, 115(2884), 195\u2013199." },
  { id: "20", text: "White, T.D. et al. (2009). Ardipithecus ramidus and the paleobiology of early hominids. Science, 326(5949), 64\u201386." },
  { id: "21", text: "Leakey, L.S.B. (1959). A new fossil skull from Olduvai. Nature, 184(4685), 491\u2013493." },
  { id: "22", text: "Green, D.J. & Alemseged, Z. (2012). Australopithecus afarensis scapular ontogeny, function, and the role of climbing in human evolution. Science, 338(6106), 514\u2013517." },
  { id: "23", text: "Haile-Selassie, Y. et al. (2010). An early Australopithecus afarensis postcranium from Woranso-Mille, Ethiopia. Proceedings of the National Academy of Sciences, 107(27), 12121\u201312126." },
  { id: "24", text: "Latimer, B. & Lovejoy, C.O. (1989). The calcaneus of Australopithecus afarensis and its implications for the evolution of bipedality. American Journal of Physical Anthropology, 78(3), 369\u2013386." },
] as const;
