export const ESSAY_META = {
  title: 'Turkana Boy: The First Modern Body',
  subtitle: '108 bones, one damaged jaw, and the child who made distance human',
  category: 'Science',
  subcategory: 'Paleoanthropology',
  readTime: '30 min',
  sourceCount: 16,
  sourceTier: 'Tier-1/2',
  sectionCount: 10,
  visualizationCount: 7,
  designSystem: 'Subject-derived',
  published: 'March 2026',
  model: 'claude-opus-4.6',
  spec: 'turkana-boy',
  variant: 'claude-opus-4-6',
  canonicalHref: '/essays/science/turkana-boy',
  template: 'Visual Essay',
  authorship: {
    mode: 'ai-directed' as const,
    director: { name: 'Zev Uhuru' },
    model: 'claude-opus-4.6',
    aiContributions: ['research', 'code', 'visualization'],
  },
  backLink: '/essays',
  backLabel: 'Essays',
  clusterParent: {
    slug: 'seven-million-years',
    title: 'Seven Million Years',
    route: '/essays/science/seven-million-years',
  },
  palette: [
    { name: 'Strata', color: '#0F1114' },
    { name: 'Bone', color: '#EDE2D0' },
    { name: 'Sediment', color: '#B8A07A' },
    { name: 'Lake', color: '#4A8C8C' },
    { name: 'Heat', color: '#D4803A' },
    { name: 'Charcoal', color: '#262B30' },
    { name: 'Dust', color: '#F0E6D4' },
    { name: 'Accent', color: '#C45A2D' },
  ],
  visualizations: [
    { name: 'Skeletal Completeness Reveal', type: 'Interactive SVG' },
    { name: 'Age Discrepancy Comparison', type: 'D3 + SVG' },
    { name: 'Growth Projection Chart', type: 'Recharts Area Chart' },
    { name: 'Body Proportion Comparison', type: 'Recharts Bar Chart' },
    { name: 'Brain Volume Context', type: 'Recharts Bar Chart' },
    { name: 'Voice Debate Timeline', type: 'Annotated SVG' },
    { name: 'Migration Route Map', type: 'D3-Geo SVG' },
  ],
  keySources: [
    'Brown et al. 1985, Nature — first report of KNM-WT 15000',
    'Walker and Leakey 1993 — Nariokotome skeleton monograph',
    'Smith 1993 — dental versus skeletal age discrepancy',
    'Ruff and Walker 1993 — body size and shape analysis',
    'Wheeler 1991, 1993 — thermoregulation and body form',
    'Meyer and Haeusler 2015 — spinal cord evolution and dysplasia',
    'Pontzer 2012 — ecological energetics in early Homo',
    'Lordkipanidze et al. 2007 — Dmanisi postcranial evidence',
  ],
};
