/**
 * Image assets for "The History, Evolution, and Authenticity of Burmese Cuisine"
 * All images sourced with proper licensing verification per Image Research & Licensing Expert standards
 */

export interface ImageAsset {
  url: string;
  alt: string;
  attribution: string;
  license: string;
  source: string;
  chapter?: number;
  category: 'historical' | 'food' | 'cultural' | 'portrait' | 'landscape';
}

// ============================================================================
// HISTORICAL IMAGES
// ============================================================================

export const historicalImages: Record<string, ImageAsset> = {
  mandalayPalace: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/6/68/Mandalay_Palace_Hluttaw_1886.jpg',
    alt: 'Palace of the Hluttaw (Supreme Council) at Mandalay, 1886',
    attribution: 'The Illustrated London News, 1886',
    license: 'Public Domain',
    source: 'Wikimedia Commons',
    chapter: 6,
    category: 'historical',
  },
  kingMindon: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/a/a6/King_Mindon_Min.jpg',
    alt: 'Portrait of King Mindon Min of Burma',
    attribution: 'Unknown photographer, 19th century',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 6,
    category: 'portrait',
  },
  queenSupayalat: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/9/91/Queen_Supayalat.jpg',
    alt: 'Portrait of Queen Supayalat, last Queen of Burma, c. 1882',
    attribution: 'Unknown photographer, c. 1882',
    license: 'Public Domain',
    source: 'Wikimedia Commons',
    chapter: 6,
    category: 'portrait',
  },
  kingThibawAndQueen: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/4/49/King_Thibaw_and_Queen_SupayaLat.jpg',
    alt: 'King Thibaw and Queen Supayalat, c. 1880',
    attribution: 'Unknown photographer, c. 1880',
    license: 'Public Domain',
    source: 'Wikimedia Commons',
    chapter: 6,
    category: 'portrait',
  },
  georgeOrwell: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/8/82/George_Orwell%2C_c._1940_%2841928180381%29.jpg',
    alt: 'George Orwell, c. 1940',
    attribution: 'Unknown photographer, c. 1940',
    license: 'Public Domain',
    source: 'Wikimedia Commons',
    chapter: 6,
    category: 'portrait',
  },
  baganMural: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/0/05/2013_Myanmar_Luyten-De-Hauwere_Bagan_019_gupyaukgyi_myinkaba_temple_mural.jpg',
    alt: 'Ancient mural from Gubyaukgyi Temple, Myinkaba, Bagan',
    attribution: 'Chris and Denis Luyten-De Hauwere, 2013',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 6,
    category: 'historical',
  },
  somingyiMural: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Somingyi_interior_mural_%28143239%29.jpg',
    alt: 'Interior mural of Somingyi Kyaung Temple, Bagan',
    attribution: 'Tore Sætre, 2013',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 6,
    category: 'historical',
  },
  anandaTemple: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Bagan%2C_Myanmar%2C_Ananda_Temple_as_seen_from_Thatbyinnyu_Temple_in_Bagan_plains.jpg',
    alt: 'Ananda Temple as seen from Thatbyinnyu Temple, Bagan plains',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 6,
    category: 'historical',
  },
  shwedagonPagoda: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/1/14/DSC010_Myanmar_Yangon_Paya_Shw%C3%A9dagon_Pagoda_Main_Golden_Stupa_%287181923090%29.jpg',
    alt: 'Shwedagon Pagoda golden stupa, Yangon - the most sacred Buddhist pagoda in Myanmar',
    attribution: 'Dennis Jarvis, 2012',
    license: 'CC BY-SA 2.0',
    source: 'Wikimedia Commons',
    chapter: 6,
    category: 'historical',
  },
  yangonColonial: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/3/3c/Yangon%2C_Colonial_town_core%2C_Strand_Road%2C_Myanmar.jpg',
    alt: 'Colonial architecture on Strand Road, downtown Yangon',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 6,
    category: 'historical',
  },
  burmeseLady1890s: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/6/67/Burmese_lady_in_traditional_costume_in_the_1890s.jpg',
    alt: 'Burmese lady in traditional costume, 1890s - colonial era portrait',
    attribution: 'Unknown photographer, 1890s',
    license: 'Public Domain',
    source: 'Wikimedia Commons',
    chapter: 6,
    category: 'portrait',
  },
};

// ============================================================================
// FOOD PHOTOGRAPHY
// ============================================================================

export const foodImages: Record<string, ImageAsset> = {
  mohinga: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/4/40/Myanmar%E2%80%99s_Traditional_Food_-_Mohinga.jpg',
    alt: 'Mohinga - Myanmar\'s traditional national dish, fish noodle soup',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 3,
    category: 'food',
  },
  mohingaStall: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Mohinga_stall%2C_Mandalay%2C_Myanmar.JPG',
    alt: 'Mohinga street stall in Mandalay, Myanmar',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 3.0',
    source: 'Wikimedia Commons',
    chapter: 3,
    category: 'food',
  },
  mohingaAndLaphet: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Mohinga_soup_and_tea_leaf_salad_A_Nyar_Tar.jpg',
    alt: 'Mohinga soup served alongside tea leaf salad (laphet thoke)',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 3,
    category: 'food',
  },
  burmeseMeal: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Burmese_meal.JPG',
    alt: 'Traditional Burmese meal with rice, curries, ngapi yay-jo, and vegetables',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 3.0',
    source: 'Wikimedia Commons',
    chapter: 2,
    category: 'food',
  },
  burmeseCurrySet: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/a/a8/Myanma_cuisine_%28cropped%29.jpg',
    alt: 'Traditional Burmese curry set with soup, rice, vegetables, and various curries',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 2,
    category: 'food',
  },
  teaHouseFood: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/6/64/Myanmar_Tea_House_Food.jpg',
    alt: 'Tea house food - spring rolls, steamed pork, and traditional Myanmar tea',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 7,
    category: 'food',
  },
  shanTofu: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Plate_of_Hnapyan_Gyaw_%28Hpaungdaw_U_Pagoda%2C_Inle_Lake%2C_Shan_States%2C_Myanmar%29.JPG',
    alt: 'Hnapyan gyaw - Shan-style twice-fried tofu fritters from Inle Lake',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 3.0',
    source: 'Wikimedia Commons',
    chapter: 5,
    category: 'food',
  },
  shanNoodles: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/3/3f/IMG_Shanhkauksw%C3%A8.JPG',
    alt: 'Shan hkauk swè - traditional Shan-style rice noodle soup with chicken and garnishes',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 3.0',
    source: 'Wikimedia Commons',
    chapter: 5,
    category: 'food',
  },
  ohnNoKhaoSwe: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/6/64/Ohn_No_Khao_Sw%C3%A8.jpg',
    alt: 'Ohn No Khao Swè - Burmese coconut chicken noodle soup',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 5,
    category: 'food',
  },
  tofuSaladPrep: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Tofu_salad.JPG',
    alt: 'Street vendor preparing Shan tofu salad in Mandalay',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 3.0',
    source: 'Wikimedia Commons',
    chapter: 5,
    category: 'food',
  },
  driedChili: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Old_Bagan%2C_Myanmar%2C_Dried_red_chili_%28chilli%29_pepper.jpg',
    alt: 'Dried red chili peppers in Old Bagan, essential Burmese spice',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 2,
    category: 'food',
  },
  turmericDrying: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/TurmericMyanmar3.jpg',
    alt: 'Drying turmeric rhizomes - traditional processing in Myanmar',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 2,
    category: 'food',
  },
  jaggery: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Myanmar_Jaggery.jpeg',
    alt: 'Myanmar jaggery (palm sugar) - traditional sweetener from toddy palm',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 5,
    category: 'food',
  },
  burmeseSamosa: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/8/8f/Burmese_style_samusa.jpg',
    alt: 'Burmese-style samosa - Indian-influenced street food',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 5,
    category: 'food',
  },
  htaMaNae: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/6/68/Making_Hta_Ma_Nae.jpg',
    alt: 'Making Hta Ma Nae - traditional Mon sticky rice delicacy',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 3,
    category: 'food',
  },
  oiledGlutinousRice: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Burmese_Oiled_Glutinous_Rice.jpg',
    alt: 'Burmese oiled glutinous rice with beans and fried fish',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 2,
    category: 'food',
  },
  paungDin: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Paung_din.JPG',
    alt: 'Paung din - glutinous rice cooked in bamboo tubes',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 3.0',
    source: 'Wikimedia Commons',
    chapter: 4,
    category: 'food',
  },
  friedSnack: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Myanmar_Fried_Snack.jpg',
    alt: 'Myanmar fried snacks - deep-fried vegetables and street food',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 7,
    category: 'food',
  },
  naanByaMutton: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/0/01/Naan_bya_with_mutton_soup.JPG',
    alt: 'Naan bya with mutton soup - Indian-influenced Burmese breakfast',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 3.0',
    source: 'Wikimedia Commons',
    chapter: 5,
    category: 'food',
  },
  // Transformation comparison images for Chapter 5
  indianSamosa: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Samosa-Indian-popular-snack.jpg',
    alt: 'Traditional Indian samosa - deep-fried potato-filled pastry',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 5,
    category: 'food',
  },
  indianNaan: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Tandoor-flatbread-inside-the-tandoor-oven.jpg',
    alt: 'Indian naan bread being baked in a tandoor oven',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 5,
    category: 'food',
  },
  myanmarFoodVariety: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Myanmar_food.jpg',
    alt: 'Variety of traditional Myanmar foods including desserts',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 8,
    category: 'food',
  },
};

// ============================================================================
// CULTURAL & DOCUMENTARY IMAGES
// ============================================================================

export const culturalImages: Record<string, ImageAsset> = {
  yangonTeahouse: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/8/8e/Yangon_Teahouse_%288395084892%29.jpg',
    alt: 'Traditional teahouse interior in Yangon, Myanmar',
    attribution: 'Unknown photographer',
    license: 'CC BY 2.0',
    source: 'Wikimedia Commons',
    chapter: 7,
    category: 'cultural',
  },
  bogyokeMarket: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/9/98/Bogyoke_Aung_San_Market_inside.jpg',
    alt: 'Interior of Bogyoke Aung San Market (Scott Market), Yangon',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 5,
    category: 'cultural',
  },
  sittweMarket: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/6/62/Fish_Market_Scene_-_Sittwe_-_Rakhaing_%28Arakan%29_State_-_Myanmar_%28Burma%29_%2812231913203%29.jpg',
    alt: 'Fish market scene in Sittwe, Rakhine State',
    attribution: 'Adam Jones, 2014',
    license: 'CC BY-SA 2.0',
    source: 'Wikimedia Commons',
    chapter: 1,
    category: 'cultural',
  },
  driedFishSittwe: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Dried_Fish_for_Sale_-_Sittwe_-_Rakhaing_%28Arakan%29_State_-_Myanmar_%28Burma%29_%2812232011904%29.jpg',
    alt: 'Dried fish for sale at Sittwe fish market - raw materials for ngapi production',
    attribution: 'Adam Jones, 2014',
    license: 'CC BY-SA 2.0',
    source: 'Wikimedia Commons',
    chapter: 1,
    category: 'cultural',
  },
  streetFoodVendor: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/6/66/Street_food_vendor_in_Yangon.jpg',
    alt: 'Street food vendor in Yangon, Myanmar',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 3,
    category: 'cultural',
  },
  inleFloatingMarket: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Inle_Floating_market.jpg',
    alt: 'Floating market at Inle Lake, Shan State',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 5,
    category: 'cultural',
  },
  traditionalStove: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/1/10/Myanmar_traditional_stove.jpg',
    alt: 'Traditional Myanmar cooking stove made of brick with charcoal',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 2,
    category: 'cultural',
  },
  inleFisherman: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Inle_Lake%2C_Fisherman%2C_Myanmar.jpg',
    alt: 'Traditional Intha leg-rowing fisherman on Inle Lake',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 4,
    category: 'cultural',
  },
  mandalayNightMarket: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/2/22/Mandalay_--_Night_Market.JPG',
    alt: 'Night market scene in Mandalay with traditional Burmese foods',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 3.0',
    source: 'Wikimedia Commons',
    chapter: 3,
    category: 'cultural',
  },
  villageKitchen: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/6/69/Pangetkon%2C_Shan_Hills%2C_Myanmar%2C_Village_kitchen_in_rural_remote_area_of_Shan_Hills_near_Kalaw.jpg',
    alt: 'Traditional village kitchen in the Shan Hills near Kalaw',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 4,
    category: 'cultural',
  },
  rakhineCoast: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Andrew_Bay%2C_Rakhine_State.jpg',
    alt: 'Fishing boats in Andrew Bay, Rakhine State coastal waters',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 1,
    category: 'cultural',
  },
  irrawaddyRiver: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/c/cf/View_of_Irrawaddy_River.jpg',
    alt: 'View of Irrawaddy River from Bagan - Myanmar\'s lifeline',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 6,
    category: 'landscape',
  },
  lacquerwareWorkers: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/Bagan-Lacquerware-Factory-Workers.JPG',
    alt: 'Workers at Bagan lacquerware factory - traditional craft',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 3.0',
    source: 'Wikimedia Commons',
    chapter: 6,
    category: 'cultural',
  },
  lacquerwareCollection: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Burmese_lacquerware.JPG',
    alt: 'Collection of traditional Burmese lacquerware vessels',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 3.0',
    source: 'Wikimedia Commons',
    chapter: 6,
    category: 'cultural',
  },
  thanakaWoman: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/c/c6/Thanaka_cosmetic_paste.jpg',
    alt: 'Young woman wearing thanaka cosmetic paste - traditional beauty',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 7,
    category: 'cultural',
  },
  monksAlmsgiving: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/4/40/Almsgiving%2C_Nyaungshwe%2C_Myanmar.jpg',
    alt: 'Buddhist monks receiving alms in Nyaungshwe - food and spirituality',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 7,
    category: 'cultural',
  },
  clayPot: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/8/81/Myanmar_water_clay_pot.jpg',
    alt: 'Traditional Myanmar clay pots - used for storage and fermentation',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 1,
    category: 'cultural',
  },
  kachinWomen: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/c/c6/Kachin_women_in_traditional_dress.jpg',
    alt: 'Kachin women in traditional dress - ethnic diversity of Myanmar',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 5,
    category: 'cultural',
  },
  shanRicePaddies: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Shan_Hills%2C_Myanmar%2C_Rice_paddies_in_rural_Myanmar_between_Inle_lake_and_Kalaw_mountain_range.jpg',
    alt: 'Rice paddies in the Shan Hills between Inle Lake and Kalaw',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 4,
    category: 'landscape',
  },
  chinStateRice: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/e/e2/Rice_paddy%2C_Chin_State%2C_Myanmar.jpg',
    alt: 'Rice paddy in Chin State - highland agriculture',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 5,
    category: 'landscape',
  },
  malikhaRiver: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/9/90/Malikha_River%2C_Northern_Kachin_State..JPG',
    alt: 'Malikha River flowing through northern Kachin State highlands',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 3.0',
    source: 'Wikimedia Commons',
    chapter: 5,
    category: 'landscape',
  },
  rakhineMonTiVendor: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Rakhine_mont_ti_street_vendor.jpg',
    alt: 'Rakhine mont ti street vendor in Yangon',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 3,
    category: 'cultural',
  },
  inleLakeMarket: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/1/17/Rural_farmer_market_traditional_retail_Ywama_Inle_Lake_Myanmar.jpg',
    alt: 'Traditional farmer market at Ywama, Inle Lake',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 4,
    category: 'cultural',
  },
  hsipawVegetableMarket: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/9/93/Vegetable_market_near_the_river._%2814896489901%29.jpg',
    alt: 'Vegetable market near the river in Hsipaw',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 2.0',
    source: 'Wikimedia Commons',
    chapter: 5,
    category: 'cultural',
  },
  goldenRock: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Golden_rock_Kyaiktiyo_Pagoda.JPG',
    alt: 'Kyaiktiyo Pagoda (Golden Rock) - sacred Mon State pilgrimage site',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 3.0',
    source: 'Wikimedia Commons',
    chapter: 6,
    category: 'cultural',
  },
  uBeinBridge: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/e/eb/U-Bein_Bridge_%2842448334405%29.jpg',
    alt: 'U Bein Bridge at Amarapura - world\'s oldest teakwood bridge',
    attribution: 'Unknown photographer',
    license: 'CC BY 2.0',
    source: 'Wikimedia Commons',
    chapter: 6,
    category: 'cultural',
  },
  paOhWomen: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Pa-Oh_women_%28Myanmar_2013%29_%2811772839553%29.jpg',
    alt: 'Pa-Oh women in traditional indigo dress selling vegetables',
    attribution: 'Unknown photographer, 2013',
    license: 'CC BY-SA 2.0',
    source: 'Wikimedia Commons',
    chapter: 5,
    category: 'cultural',
  },
  shanHillsGreenFields: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/2/2b/Shan_Hills%2C_Myanmar%2C_Green_fields_and_forest%2C_very_remote_location_in_Burma_in_western_Karen_Hills_%28Shan_Hills%29.jpg',
    alt: 'Green fields and forest in the remote Shan Hills - upland agriculture',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 4,
    category: 'landscape',
  },
  burmeseFestivalDress1907: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/4/49/Burmese_in_festival_dress_in_1907.jpg',
    alt: 'Burmese people in traditional festival dress, 1907 - historical portrait',
    attribution: 'Unknown photographer, 1907',
    license: 'Public Domain',
    source: 'Wikimedia Commons',
    chapter: 6,
    category: 'portrait',
  },
};

// ============================================================================
// LANDSCAPE IMAGES
// ============================================================================

export const landscapeImages: Record<string, ImageAsset> = {
  shanStateHighlands: {
    url: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Hsipaw%2C_Shan_State%2C_Myanmar.jpg',
    alt: 'Hsipaw town in Shan State highlands, Myanmar',
    attribution: 'Unknown photographer',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    chapter: 4,
    category: 'landscape',
  },
};

// ============================================================================
// COMBINED EXPORT BY CHAPTER
// ============================================================================

export const imagesByChapter: Record<number, ImageAsset[]> = {
  1: [
    culturalImages.sittweMarket,
    culturalImages.driedFishSittwe,
    culturalImages.rakhineCoast,
    culturalImages.clayPot,
  ],
  2: [
    foodImages.burmeseMeal,
    foodImages.burmeseCurrySet,
    culturalImages.traditionalStove,
    foodImages.driedChili,
    foodImages.turmericDrying,
    foodImages.oiledGlutinousRice,
  ],
  3: [
    foodImages.mohinga,
    foodImages.mohingaStall,
    foodImages.mohingaAndLaphet,
    culturalImages.streetFoodVendor,
    culturalImages.mandalayNightMarket,
    foodImages.htaMaNae,
    culturalImages.rakhineMonTiVendor,
  ],
  4: [
    landscapeImages.shanStateHighlands,
    culturalImages.inleFisherman,
    culturalImages.villageKitchen,
    culturalImages.shanRicePaddies,
    foodImages.paungDin,
    culturalImages.inleLakeMarket,
    culturalImages.shanHillsGreenFields,
  ],
  5: [
    culturalImages.bogyokeMarket,
    culturalImages.inleFloatingMarket,
    foodImages.shanTofu,
    foodImages.shanNoodles,
    foodImages.ohnNoKhaoSwe,
    foodImages.tofuSaladPrep,
    foodImages.burmeseSamosa,
    foodImages.jaggery,
    culturalImages.kachinWomen,
    culturalImages.chinStateRice,
    culturalImages.malikhaRiver,
    culturalImages.hsipawVegetableMarket,
    foodImages.naanByaMutton,
    culturalImages.paOhWomen,
  ],
  6: [
    historicalImages.mandalayPalace,
    historicalImages.kingMindon,
    historicalImages.queenSupayalat,
    historicalImages.kingThibawAndQueen,
    historicalImages.baganMural,
    historicalImages.somingyiMural,
    historicalImages.georgeOrwell,
    historicalImages.anandaTemple,
    historicalImages.shwedagonPagoda,
    historicalImages.yangonColonial,
    historicalImages.burmeseLady1890s,
    culturalImages.lacquerwareWorkers,
    culturalImages.lacquerwareCollection,
    culturalImages.irrawaddyRiver,
    culturalImages.goldenRock,
    culturalImages.uBeinBridge,
    culturalImages.burmeseFestivalDress1907,
  ],
  7: [
    culturalImages.yangonTeahouse,
    foodImages.teaHouseFood,
    culturalImages.thanakaWoman,
    culturalImages.monksAlmsgiving,
    foodImages.friedSnack,
  ],
  8: [
    foodImages.myanmarFoodVariety,
    // Diaspora chapter - would benefit from more contemporary overseas community photography
  ],
};

// ============================================================================
// FIGURE PORTRAITS (Historical Figures with Archival Photos)
// ============================================================================

export const figurePortraits: Record<string, ImageAsset> = {
  kingMindon: historicalImages.kingMindon,
  queenSupayalat: historicalImages.queenSupayalat,
  georgeOrwell: historicalImages.georgeOrwell,
  kingThibawAndQueen: historicalImages.kingThibawAndQueen,
};

// ============================================================================
// ALL IMAGES COMBINED
// ============================================================================

export const allImages = {
  ...historicalImages,
  ...foodImages,
  ...culturalImages,
  ...landscapeImages,
};

// ============================================================================
// IMAGE CREDITS FOR SOURCES SECTION
// ============================================================================

export const imageCredits = Object.values(allImages).map((img) => ({
  description: img.alt,
  source: img.source,
  license: img.license,
  attribution: img.attribution,
}));
