export const ESSAY_META = {
  title: 'Turkana Boy: The First Modern Body',
  subtitle: '108 Bones, a Hole in the Jaw, and the Child Who Carried Our Body Plan Into the Open World',
  category: 'Science',
  readTime: '49 min',
  sourceCount: 20,
  sourceTier: 'Tier-1',
  sectionCount: 12,
  visualizationCount: 14,
  designSystem: 'Subject-derived',
  published: 'March 2026',
  model: 'claude-opus-4.6',
  template: 'Visual Essay',
  spec: 'turkana-boy',
  backLink: '/essays',
  backLabel: 'Essays',
  clusterParent: {
    slug: 'seven-million-years',
    title: 'Seven Million Years',
    route: '/essays/science/seven-million-years',
  },
  palette: [
    { name: 'Strata Dark', color: '#111317' },
    { name: 'Fossil Lab', color: '#1A1D24' },
    { name: 'Bone Ivory', color: '#E8DCC8' },
    { name: 'Sediment Sand', color: '#C4A97D' },
    { name: 'Turkana Blue', color: '#3A8F9C' },
    { name: 'Heat Ochre', color: '#D4883A' },
    { name: 'Basin Earth', color: '#8B7355' },
    { name: 'Clinical White', color: '#F0ECE4' },
  ],
  visualizations: [
    { name: 'Skeletal Completeness', type: 'D3 + SVG Interactive' },
    { name: 'Age Dispute', type: 'D3 Split-Panel' },
    { name: 'Growth Trajectory', type: 'Recharts Line Chart' },
    { name: 'Body Proportion Comparison', type: 'D3 SVG Interactive' },
    { name: 'Thermoregulation Explainer', type: 'Interactive SVG' },
    { name: 'Locomotion Biomechanics', type: 'D3 Interactive' },
    { name: 'Brain Volume Timeline', type: 'Recharts Bar Chart' },
    { name: 'Speech Debate', type: 'D3 Two-Column Layout' },
    { name: 'Acheulean Technology Timeline', type: 'D3 Timeline' },
    { name: 'Migration Map', type: 'D3-Geo Projection' },
    { name: 'Excavation Timeline', type: 'Recharts Area Chart' },
    { name: 'Comparative Datasets Dashboard', type: 'D3 Parallel Coordinates' },
    { name: 'Cluster Context', type: 'Recharts Radar Chart' },
    { name: 'KNM-WT 15000 3D Viewer', type: 'React Three Fiber' },
  ],
  keySources: [
    'Brown et al. 1985, Nature — Original KNM-WT 15000 description',
    'Walker & Leakey (eds.) 1993 — The Nariokotome Homo erectus Skeleton',
    'Ruff & Walker 1993 — Body size and body shape',
    'Wheeler 1991, JHE — Thermoregulation and bipedalism',
    'MacLarnon & Hewitt 1999, AJPA — Spinal cord and breathing control',
    'Lepre et al. 2011, Nature — Earliest Acheulean from West Turkana',
  ],
};
